# Define services
services:
  # Database Service (Mysql)
  db:
    container_name: db

   # image: mysql:8.0
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: idm3project2024
      MYSQL_USER: idm3project2024
      MYSQL_PASSWORD: ""
    ports:
      - 3316:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  # Database Management Service (phpMyAdmin)
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"




  web:
    build: ./web/

    ports:
      - "4848:4848"
      - "8881:8080"
      - "8181:8181"
      - "5005:5005"
    depends_on:
      - db
      - phpmyadmin

    links:
      - db
      - phpmyadmin

    environment:
      MYSQL_ROOT_PASSWORD: root